# $FreeBSD$

PORTNAME=	bitlbee-mastodon
PORTVERSION=	1.4.0
CATEGORIES=	irc

MAINTAINER=	tobias.rehbein@web.de
COMMENT=	Bitlbee plugin to communicate with Mastodon instances

LICENSE=	GPLv2
LICSENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	kensanata
GH_TAGNAME=	v1.4.0

.include <bsd.port.mk>
