# $FreeBSD: head/security/py-zxcvbn/Makefile 469615 2018-05-11 07:41:58Z jbeich $

PORTNAME=	zxcvbn
PORTVERSION=	4.4.27
CATEGORIES=	security python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jbeich@FreeBSD.org
COMMENT=	Realistic password strength estimator

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils
USE_GITHUB=	yes

NO_ARCH=	yes

GH_ACCOUNT=	dwolfhub
GH_PROJECT=	zxcvbn-python
GH_TAGNAME=	v4.4.27

.include <bsd.port.mk>
